name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"     # runs daily
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: Nabhag2507
          outputs: |
            dist/github-contribution-grid-snake.svg

      - name: Push snake to output branch
        uses: EndBug/add-and-commit@v9
        with:
          add: "dist/*"
          message: "Update snake animation"
          default_author: github_actions
          push: true
